name = "ig-cookie-banner"
main = "src/worker/index.ts"
compatibility_date = "2025-02-14"

[vars]
ENVIRONMENT = "dev"
RECORD_RETENTION_DAYS = "1095"

[[d1_databases]]
binding = "DB"
database_name = "ig-consent-records"
database_id = "e236d374-7432-4823-8ade-3b2fcdfd3dd3"
migrations_dir = "migrations"

[triggers]
crons = ["0 3 * * *"]
