import { build } from "esbuild";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve } from "node:path";

const distDir = resolve(import.meta.dirname, "../dist");
const outfile = resolve(distDir, "ig-consent-banner.js");
const bannerJsModule = resolve(
  import.meta.dirname,
  "../src/worker/banner-js.ts",
);

await mkdir(distDir, { recursive: true });

await build({
  entryPoints: [resolve(import.meta.dirname, "../src/client/boot.ts")],
  bundle: true,
  minify: process.argv.includes("--minify"),
  format: "iife",
  globalName: "__igConsentBanner",
  target: "es2020",
  outfile,
  footer: {
    // Auto-invoke boot() after the IIFE loads
    js: "__igConsentBanner.boot();",
  },
});

// Read the built bundle and generate a TS module the Worker can import
const bundleContent = await readFile(outfile, "utf-8");
const moduleContent = `// Auto-generated by scripts/build-client.ts — do not edit
const BANNER_JS = ${JSON.stringify(bundleContent)};
export default BANNER_JS;
`;
await writeFile(bannerJsModule, moduleContent);

const kb = (bundleContent.length / 1024).toFixed(1);
console.log(`Built ${outfile} (${kb} KB)`);
console.log(`Generated ${bannerJsModule}`);
